### ISSUE TITLE
Fix CTabFolder Trim Calculation logic

### ISSUE THREAD

**Issue by amartya4256** [vi-eclipse/Eclipse-Platform#382]
**Description**
The CTabFolder trim is calculated using some magic numbers represented in points which can have adverse effect when scaled to pixels. Hence, it should be calculated in pixels and then converted into points using OfFloat variants to preserve inversibility.

Currently if we resize a CtabFolder (e.g. the project explorer tab), here's how the flow works:
1. CTabFolder receives WM_SIZE callback and calls updateLayout.
2. This calls CTabFolderLayout.layout.
3. CTabFolderLayout.layout -> CTabFolder.getClientArea.

Inside getClientArea, there's a call to find the trim using renderer.computeTrim with zero width and height to find the padding. It uses CTabRendering as a renderer. Hence, the call: renderer.computeTrim(CTabFolderRenderer.PART_BODY, SWT.FILL, 0, 0, 0, 0); is just a hack to obtain the padding. We need a better way to find the padding instead.

Update: Inside the computeTrim method, the paddings are added as magic numbers and they didnot scale properly on fractional scaling factors in the past but, since now we have better scaling, could it be possible that we have circumvented this problem since now these values scale properly with the new implementation in DPIUtils.

**Comment by akoch-yatta** [comment]
@amartya4256 What is the state of this? probably still necessary, isn't it? If yes, fill the TODO please 😄

**Comment by amartya4256** [comment]
Let's wait for the Point. OfFloat fix from https://github.com/eclipse-platform/eclipse.platform.swt/pull/2502, since it seems indirectly related. The trim is needed to compute size and the trim is represented in Point (as size), which might be fixed using the Point.OfFloat.asSize() and Point.OfFloat.asLocation() variants. I'll add it in the description.

**Comment by fedejeanne** [comment]
I assigned the Milestone **M3** only so that this one is not forgotten. We can re-prioritize after @amartya4256 has found a way to reproduce the error (or found out that the error is not reproducible anymore).

**Comment by amartya4256** [comment]
I tried reproducing the CTabFolder flickerig issue. Could it be that it's already fixed by @HeikoKlare 's changes in pointToPixel and pixelToPoint implementations? I cannot reproduce it anymore. In that case. Do we even need this issue?

**Comment by HeikoKlare** [comment]
As discussed: iirc the issue was never experiencable (or only for short periods of time and independent from this issue). This issue was raised because when working a different issue (something related to using OfFloat types "everywhere"), an issue with the CTabFolder arised, which could traced back to an issue with the trim calculation. For that reason, we created this ticket to investigate what may be conceptually wrong with the trim calculation (no matter whether it produced directly visible issues with the current pixel/point conversion implementations or not).

**Comment by amartya4256** [comment]
I have updated the description on the basis of my observations.

**Comment by HeikoKlare** [comment]
I have to admit that I still do not fully understand the issue. `computeTrim()` returns point values and the calculation is fully based on point values without any of them being converted from pixels (if I am not mistaken). I don't see how using pixel values and then converting to points could give any better results as more rounding (which could by accident lead to better or worse results) would be involved then. Would it be about calculating on pixels to use the same kind of rounding used at other places for the current zoom so that imprecision evens out? And if yes, would we be sure that this is actually the case and that we do not introduce more roundings that even make the situation worse? I think we are still lacking a holistic concept of when/where/how rounding should happen and it's more a local decision of individual operation what leads to least worse results.

Anyway, what is the need or proposal to proceed here? IIRC you had concrete values for the trim calculation that showed some imprecision. Such a concrete scenario would help to better understand what's actually going wrong.

**Comment by amartya4256** [comment]
Since we discussed about it and came to a conclusion that the problem mostly comes because setBounds doesn't function as intended hence we should working on fixing setBounds and trim logic doesn't need to be changed. So closing this issue.
